name: tarachat
services:
  backend:
    volumes:
      - ./backend:/app
    command: uvicorn --host=0.0.0.0 --port=8000 tarachat.main:app --log-config=/app/log-config.dev.yaml --reload

  frontend:
    image: node:18-alpine
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: npm run dev
    working_dir: /app
