name: tarachat
services:
  nginx:
    build: nginx
    depends_on:
      backend:
        condition: service_healthy
      certbot:
        condition: service_healthy
      frontend:
        condition: service_started
    volumes:
      - certbot-www:/web:ro
      - certbot-certs:/etc/letsencrypt:ro
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    networks:
      default:
        aliases:
          - tarachat-nginx
    restart: always

  certbot:
    image: certbot/certbot:v5.4.0
    volumes:
      - ./certbot/deploy-hook.sh:/deploy-hook.sh:ro
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/html
    environment:
      - HOSTNAME=${HOSTNAME}
    entrypoint: ""
    command: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot --webroot-path=/var/www/html --deploy-hook /deploy-hook.sh;
        sleep 12h;
      done"
    restart: always
    healthcheck:
      test: [ "CMD", "test", "-e", "/etc/letsencrypt/live/fullchain.pem" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 15

  backend:
    build: backend
    volumes:
      - backend-cache:/root/.cache
    networks:
      default:
        aliases:
          - tarachat-backend
    command: uvicorn --host=0.0.0.0 --port=80 tarachat.app:app --log-config=/app/log-config.yaml
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s

  frontend:
    build: frontend
    networks:
      default:
        aliases:
          - tarachat-frontend
    restart: always

networks:
  default:
    driver: bridge

volumes:
  backend-cache:
  certbot-www:
  certbot-certs:

